sudo: required
language: python
matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: nightly

install: .ci/travis.sh
script: cd tests && python$PY3 -m pytest

notifications:
    email:
        on_success: change
        on_failure: change
